name: Deploy to EC2
on: 
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Tag of the Docker Image'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Action Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.IAM_ROLE }}
        aws-region: ap-southeast-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Deploy to EC2
      env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: iorikaze-ecr-repo
          IMAGE_TAG: ${{ inputs.image-tag }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          docker stop my-container || true
          docker rm my-container || true
          docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker run -d --name my-container -p 3000:3000 $REGISTRY/$REPOSITORY:$IMAGE_TAG